### ISSUE TITLE
todo - basic setup

### ISSUE THREAD

**Issue by SandersAaronD** [grafana/ai-training-o11y#1]
```[tasklist]
### Tasks
- [ ] finalize spinup of full environment with mimir + prometheus + postgres + grafana + plugin
- [ ] flesh out the design on the postgres tables regarding process + run tracking
- [ ] dummy/basic workflows in the exporter to solidify what that flow looks like
- [ ] initialize the metadata service
- [ ] make a run work entirely between the metadata service and the exporter
- [ ] port existing work over the the hackathon project
- [ ] make sure the plugin can connect to the metadata service, and especially can give back a login string from the metadata service to the user
- [ ] make the dataviz at least tolerable
```
