### ISSUE TITLE
TODO to give to customer

### ISSUE THREAD

**Issue by SandersAaronD** [grafana/ai-training-o11y#89]
- [ ] UI fixes #86 
- [ ] Expose token in UI #87
- [ ] Make model metric queries scale #88
- [ ] Set up written onboarding instructions for both ourselves and users for adding the plugin to a stack, configuring it, and using the python exporter.
